"""Initial

Revision ID: 589b8b8abdaa
Revises: 
Create Date: 2023-12-18 00:13:19.335985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589b8b8abdaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('input_balance',
    sa.Column('input_balance_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Float(), nullable=False),
    sa.Column('passive', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('input_balance_id'),
    sa.UniqueConstraint('active'),
    sa.UniqueConstraint('passive')
    )
    op.create_table('turnover',
    sa.Column('turnover_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('turnover_id'),
    sa.UniqueConstraint('credit'),
    sa.UniqueConstraint('debit')
    )
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('unid', sa.Integer(), nullable=False),
    sa.Column('input_balance_id', sa.Integer(), nullable=False),
    sa.Column('turnover_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['input_balance_id'], ['input_balance.input_balance_id'], ),
    sa.ForeignKeyConstraint(['turnover_id'], ['turnover.turnover_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('turnover')
    op.drop_table('input_balance')
    op.drop_table('class')
    # ### end Alembic commands ###
